/* =========================================================================
   DADOS DOS PAÍSES  —  "O Mundo, Continente a Continente"
   -------------------------------------------------------------------------
   Lista JSON dentro de uma variável (window.PAISES). A única diferença para
   um .json puro é a linha de atribuição no início — assim o livro abre
   directamente do disco (file://), sem servidor web.

   Cada entrada:
     nome        nome em português
     endonimo    nome na(s) língua(s) oficial(is) (romanização + grafia nativa)
     iso         código de 2 letras, minúsculas (bandeira + mapa)
     capital     capital (ou sede de governo)
     continente  africa | america | asia | europa | oceania
     soberania   (só territórios) Estado a que pertence

   - Estados soberanos + alguns territórios com bandeira própria.
   - A ORDEM dentro de cada continente é alfabética (livro de consulta).
   - A ordem dos continentes no livro é definida em index.html.
   ========================================================================= */
window.PAISES = [

  /* ===================== EUROPA ===================== */
  { "nome":"Albânia", "endonimo":"Shqipëria", "iso":"al", "capital":"Tirana", "continente":"europa", "idioma":"Albanês", "populacao":2740000, "area":28748 },
  { "nome":"Alemanha", "endonimo":"Deutschland", "iso":"de", "capital":"Berlim", "continente":"europa", "idioma":"Alemão", "populacao":84500000, "area":357590 },
  { "nome":"Andorra", "endonimo":"Andorra", "iso":"ad", "capital":"Andorra-a-Velha", "continente":"europa", "idioma":"Catalão", "populacao":81000, "area":468 },
  { "nome":"Áustria", "endonimo":"Österreich", "iso":"at", "capital":"Viena", "continente":"europa", "idioma":"Alemão", "populacao":9130000, "area":83879 },
  { "nome":"Bélgica", "endonimo":"België · Belgique · Belgien", "iso":"be", "capital":"Bruxelas", "continente":"europa", "idioma":"Neerlandês, francês e alemão", "populacao":11750000, "area":30528 },
  { "nome":"Bielorrússia", "endonimo":"Bielarus (Беларусь)", "iso":"by", "capital":"Minsk", "continente":"europa", "idioma":"Bielorrusso e russo", "populacao":9200000, "area":207600 },
  { "nome":"Bósnia e Herzegovina", "endonimo":"Bosna i Hercegovina (Босна и Херцеговина)", "iso":"ba", "capital":"Sarajevo", "continente":"europa", "idioma":"Bósnio, croata e sérvio", "populacao":3170000, "area":51197 },
  { "nome":"Bulgária", "endonimo":"Balgariya (България)", "iso":"bg", "capital":"Sófia", "continente":"europa", "idioma":"Búlgaro", "populacao":6440000, "area":110994 },
  { "nome":"Chéquia", "endonimo":"Česko", "iso":"cz", "capital":"Praga", "continente":"europa", "idioma":"Checo", "populacao":10870000, "area":78871 },
  { "nome":"Cidade do Vaticano", "endonimo":"Città del Vaticano", "iso":"va", "capital":"Vaticano", "continente":"europa", "idioma":"Italiano (latim, na Santa Sé)", "populacao":800, "area":0.49 },
  { "nome":"Croácia", "endonimo":"Hrvatska", "iso":"hr", "capital":"Zagrebe", "continente":"europa", "idioma":"Croata", "populacao":3850000, "area":56594 },
  { "nome":"Dinamarca", "endonimo":"Danmark", "iso":"dk", "capital":"Copenhaga", "continente":"europa", "idioma":"Dinamarquês", "populacao":5960000, "area":43094 },
  { "nome":"Eslováquia", "endonimo":"Slovensko", "iso":"sk", "capital":"Bratislava", "continente":"europa", "idioma":"Eslovaco", "populacao":5420000, "area":49035 },
  { "nome":"Eslovénia", "endonimo":"Slovenija", "iso":"si", "capital":"Liubliana", "continente":"europa", "idioma":"Esloveno", "populacao":2120000, "area":20273 },
  { "nome":"Espanha", "endonimo":"España", "iso":"es", "capital":"Madrid", "continente":"europa", "idioma":"Espanhol", "populacao":48450000, "area":505990 },
  { "nome":"Estónia", "endonimo":"Eesti", "iso":"ee", "capital":"Taline", "continente":"europa", "idioma":"Estónio", "populacao":1370000, "area":45335 },
  { "nome":"Finlândia", "endonimo":"Suomi · Finland", "iso":"fi", "capital":"Helsínquia", "continente":"europa", "idioma":"Finlandês e sueco", "populacao":5580000, "area":338455 },
  { "nome":"França", "endonimo":"France", "iso":"fr", "capital":"Paris", "continente":"europa", "idioma":"Francês", "populacao":68400000, "area":551695 },
  { "nome":"Grécia", "endonimo":"Elláda (Ελλάδα)", "iso":"gr", "capital":"Atenas", "continente":"europa", "idioma":"Grego", "populacao":10400000, "area":131957 },
  { "nome":"Hungria", "endonimo":"Magyarország", "iso":"hu", "capital":"Budapeste", "continente":"europa", "idioma":"Húngaro", "populacao":9580000, "area":93028 },
  { "nome":"Irlanda", "endonimo":"Éire · Ireland", "iso":"ie", "capital":"Dublin", "continente":"europa", "idioma":"Irlandês e inglês", "populacao":5300000, "area":70273 },
  { "nome":"Islândia", "endonimo":"Ísland", "iso":"is", "capital":"Reiquiavique", "continente":"europa", "idioma":"Islandês", "populacao":390000, "area":103000 },
  { "nome":"Itália", "endonimo":"Italia", "iso":"it", "capital":"Roma", "continente":"europa", "idioma":"Italiano", "populacao":58900000, "area":301340 },
  { "nome":"Kosovo", "endonimo":"Kosova · Kosovo", "iso":"xk", "capital":"Pristina", "continente":"europa", "idioma":"Albanês e sérvio", "populacao":1600000, "area":10887 },
  { "nome":"Letónia", "endonimo":"Latvija", "iso":"lv", "capital":"Riga", "continente":"europa", "idioma":"Letão", "populacao":1870000, "area":64589 },
  { "nome":"Listenstaine", "endonimo":"Liechtenstein", "iso":"li", "capital":"Vaduz", "continente":"europa", "idioma":"Alemão", "populacao":40000, "area":160 },
  { "nome":"Lituânia", "endonimo":"Lietuva", "iso":"lt", "capital":"Vílnius", "continente":"europa", "idioma":"Lituano", "populacao":2860000, "area":65300 },
  { "nome":"Luxemburgo", "endonimo":"Lëtzebuerg · Luxembourg · Luxemburg", "iso":"lu", "capital":"Luxemburgo", "continente":"europa", "idioma":"Luxemburguês, francês e alemão", "populacao":672000, "area":2586 },
  { "nome":"Macedónia do Norte", "endonimo":"Severna Makedonija (Северна Македонија)", "iso":"mk", "capital":"Escópia", "continente":"europa", "idioma":"Macedónio", "populacao":1830000, "area":25713 },
  { "nome":"Malta", "endonimo":"Malta", "iso":"mt", "capital":"Valeta", "continente":"europa", "idioma":"Maltês e inglês", "populacao":542000, "area":316 },
  { "nome":"Moldávia", "endonimo":"Moldova", "iso":"md", "capital":"Chișinău", "continente":"europa", "idioma":"Romeno", "populacao":2510000, "area":33846 },
  { "nome":"Mónaco", "endonimo":"Monaco", "iso":"mc", "capital":"Mónaco", "continente":"europa", "idioma":"Francês", "populacao":38350, "area":2 },
  { "nome":"Montenegro", "endonimo":"Crna Gora (Црна Гора)", "iso":"me", "capital":"Podgorica", "continente":"europa", "idioma":"Montenegrino", "populacao":617000, "area":13812 },
  { "nome":"Noruega", "endonimo":"Norge · Noreg", "iso":"no", "capital":"Oslo", "continente":"europa", "idioma":"Norueguês", "populacao":5550000, "area":385207 },
  { "nome":"Países Baixos", "endonimo":"Nederland", "iso":"nl", "capital":"Amesterdão", "continente":"europa", "idioma":"Neerlandês", "populacao":17950000, "area":41850 },
  { "nome":"Polónia", "endonimo":"Polska", "iso":"pl", "capital":"Varsóvia", "continente":"europa", "idioma":"Polaco", "populacao":36700000, "area":312700 },
  { "nome":"Portugal", "endonimo":"Portugal", "iso":"pt", "capital":"Lisboa", "continente":"europa", "idioma":"Português", "populacao":10467000, "area":92230 },
  { "nome":"Reino Unido", "endonimo":"United Kingdom", "iso":"gb", "capital":"Londres", "continente":"europa", "idioma":"Inglês", "populacao":68350000, "area":243610 },
  { "nome":"Roménia", "endonimo":"România", "iso":"ro", "capital":"Bucareste", "continente":"europa", "idioma":"Romeno", "populacao":19000000, "area":238398 },
  { "nome":"Rússia", "endonimo":"Rossiya (Россия)", "iso":"ru", "capital":"Moscovo", "continente":"europa", "idioma":"Russo", "populacao":143800000, "area":17098246 },
  { "nome":"San Marino", "endonimo":"San Marino", "iso":"sm", "capital":"Cidade de San Marino", "continente":"europa", "idioma":"Italiano", "populacao":33600, "area":61 },
  { "nome":"Sérvia", "endonimo":"Srbija (Србија)", "iso":"rs", "capital":"Belgrado", "continente":"europa", "idioma":"Sérvio", "populacao":6620000, "area":77474 },
  { "nome":"Suécia", "endonimo":"Sverige", "iso":"se", "capital":"Estocolmo", "continente":"europa", "idioma":"Sueco", "populacao":10550000, "area":450295 },
  { "nome":"Suíça", "endonimo":"Schweiz · Suisse · Svizzera · Svizra", "iso":"ch", "capital":"Berna", "continente":"europa", "idioma":"Alemão, francês, italiano e romanche", "populacao":8850000, "area":41285 },
  { "nome":"Ucrânia", "endonimo":"Ukraïna (Україна)", "iso":"ua", "capital":"Kiev", "continente":"europa", "idioma":"Ucraniano", "populacao":38000000, "area":603628 },
  { "nome":"Ilhas Faroé", "endonimo":"Føroyar", "iso":"fo", "capital":"Tórshavn", "continente":"europa", "soberania":"Dinamarca", "idioma":"Feroês e dinamarquês", "populacao":54149, "area":1399 },
  { "nome":"Gibraltar", "endonimo":"Gibraltar", "iso":"gi", "capital":"Gibraltar", "continente":"europa", "soberania":"Reino Unido", "idioma":"Inglês", "populacao":34003, "area":6.84 },
  { "nome":"Ilha de Man", "endonimo":"Mannin · Isle of Man", "iso":"im", "capital":"Douglas", "continente":"europa", "soberania":"Coroa britânica", "idioma":"Inglês (e manquês)", "populacao":84523, "area":572 },
  { "nome":"Jersey", "endonimo":"Jersey · Jèrri", "iso":"je", "capital":"Saint Helier", "continente":"europa", "soberania":"Coroa britânica", "idioma":"Inglês e francês", "populacao":103267, "area":118 },
  { "nome":"Guernsey", "endonimo":"Guernsey · Guernési", "iso":"gg", "capital":"St. Peter Port", "continente":"europa", "soberania":"Coroa britânica", "idioma":"Inglês e francês", "populacao":67787, "area":78 },
  { "nome":"Alanda", "endonimo":"Åland", "iso":"ax", "capital":"Mariehamn", "continente":"europa", "soberania":"Finlândia", "idioma":"Sueco", "populacao":30836, "area":1583 },

  /* ===================== ÁFRICA ===================== */
  { "nome":"África do Sul", "endonimo":"South Africa · Suid-Afrika · iNingizimu Afrika", "iso":"za", "capital":"Pretória · Cidade do Cabo · Bloemfontein", "continente":"africa", "idioma":"11 línguas (inglês, zulu, xhosa…)", "populacao":62027503, "area":1221037 },
  { "nome":"Angola", "endonimo":"Angola", "iso":"ao", "capital":"Luanda", "continente":"africa", "idioma":"Português", "populacao":36749906, "area":1246700 },
  { "nome":"Argélia", "endonimo":"Al-Jazair (الجزائر)", "iso":"dz", "capital":"Argel", "continente":"africa", "idioma":"Árabe e berbere", "populacao":46164219, "area":2381741 },
  { "nome":"Benim", "endonimo":"Bénin", "iso":"bj", "capital":"Porto-Novo", "continente":"africa", "idioma":"Francês", "populacao":14111034, "area":114763 },
  { "nome":"Botsuana", "endonimo":"Botswana", "iso":"bw", "capital":"Gaborone", "continente":"africa", "idioma":"Inglês e tswana", "populacao":2480244, "area":581737 },
  { "nome":"Burquina Faso", "endonimo":"Burkina Faso", "iso":"bf", "capital":"Uagadugu", "continente":"africa", "idioma":"Francês", "populacao":23025776, "area":274200 },
  { "nome":"Burúndi", "endonimo":"Uburundi · Burundi", "iso":"bi", "capital":"Gitega", "continente":"africa", "idioma":"Kirundi e francês", "populacao":13689450, "area":27834 },
  { "nome":"Cabo Verde", "endonimo":"Cabo Verde", "iso":"cv", "capital":"Praia", "continente":"africa", "idioma":"Português (e crioulo cabo-verdiano)", "populacao":555988, "area":4033 },
  { "nome":"Camarões", "endonimo":"Cameroun · Cameroon", "iso":"cm", "capital":"Iaundé", "continente":"africa", "idioma":"Francês e inglês", "populacao":28372687, "area":475442 },
  { "nome":"Chade", "endonimo":"Tchad · Tšād", "iso":"td", "capital":"Jamena", "continente":"africa", "idioma":"Árabe e francês", "populacao":19319064, "area":1284000 },
  { "nome":"Comores", "endonimo":"Komori · Juzur al-Qamar", "iso":"km", "capital":"Moroni", "continente":"africa", "idioma":"Comoriano, árabe e francês", "populacao":902348, "area":2034 },
  { "nome":"Congo", "endonimo":"Congo", "iso":"cg", "capital":"Brazzaville", "continente":"africa", "idioma":"Francês", "populacao":6142180, "area":342000 },
  { "nome":"Congo (República Democrática)", "endonimo":"Congo", "iso":"cd", "capital":"Kinshasa", "continente":"africa", "idioma":"Francês", "populacao":105789731, "area":2344858 },
  { "nome":"Costa do Marfim", "endonimo":"Côte d'Ivoire", "iso":"ci", "capital":"Yamoussoukro", "continente":"africa", "idioma":"Francês", "populacao":31165654, "area":322463 },
  { "nome":"Egito", "endonimo":"Misr (مصر)", "iso":"eg", "capital":"Cairo", "continente":"africa", "idioma":"Árabe", "populacao":114535772, "area":1010408 },
  { "nome":"Eritreia", "endonimo":"Ertra (ኤርትራ) · Iritriyā", "iso":"er", "capital":"Asmara", "continente":"africa", "idioma":"Tigrínia, árabe e inglês", "populacao":3497000, "area":117600 },
  { "nome":"Essuatíni", "endonimo":"eSwatini", "iso":"sz", "capital":"Mbabane", "continente":"africa", "idioma":"Suázi e inglês", "populacao":1230506, "area":17364 },
  { "nome":"Etiópia", "endonimo":"Ītyōṗṗyā (ኢትዮጵያ)", "iso":"et", "capital":"Adis Abeba", "continente":"africa", "idioma":"Amárico", "populacao":128691692, "area":1104300 },
  { "nome":"Gabão", "endonimo":"Gabon", "iso":"ga", "capital":"Libreville", "continente":"africa", "idioma":"Francês", "populacao":2025137, "area":267667 },
  { "nome":"Gâmbia", "endonimo":"The Gambia", "iso":"gm", "capital":"Banjul", "continente":"africa", "idioma":"Inglês", "populacao":2639916, "area":11300 },
  { "nome":"Gana", "endonimo":"Ghana", "iso":"gh", "capital":"Acra", "continente":"africa", "idioma":"Inglês", "populacao":32833031, "area":238535 },
  { "nome":"Guiné", "endonimo":"Guinée", "iso":"gn", "capital":"Conacri", "continente":"africa", "idioma":"Francês", "populacao":17521167, "area":245857 },
  { "nome":"Guiné-Bissau", "endonimo":"Guiné-Bissau", "iso":"gw", "capital":"Bissau", "continente":"africa", "idioma":"Português (e crioulo)", "populacao":1861283, "area":36125 },
  { "nome":"Guiné Equatorial", "endonimo":"Guinea Ecuatorial · Guinée équatoriale", "iso":"gq", "capital":"Malabo", "continente":"africa", "idioma":"Espanhol, francês e português", "populacao":1847549, "area":28051 },
  { "nome":"Jibuti", "endonimo":"Jībūtī · Gabuuti", "iso":"dj", "capital":"Jibuti", "continente":"africa", "idioma":"Árabe e francês", "populacao":1152944, "area":23200 },
  { "nome":"Lesoto", "endonimo":"Lesotho", "iso":"ls", "capital":"Maseru", "continente":"africa", "idioma":"Sesoto e inglês", "populacao":2007201, "area":30355 },
  { "nome":"Libéria", "endonimo":"Liberia", "iso":"lr", "capital":"Monróvia", "continente":"africa", "idioma":"Inglês", "populacao":5214030, "area":111369 },
  { "nome":"Líbia", "endonimo":"Lībiyā (ليبيا)", "iso":"ly", "capital":"Trípoli", "continente":"africa", "idioma":"Árabe", "populacao":7381023, "area":1759541 },
  { "nome":"Madagáscar", "endonimo":"Madagasikara · Madagascar", "iso":"mg", "capital":"Antananarivo", "continente":"africa", "idioma":"Malgaxe e francês", "populacao":31964956, "area":587295 },
  { "nome":"Malávi", "endonimo":"Malaŵi", "iso":"mw", "capital":"Lilongwe", "continente":"africa", "idioma":"Chicheua e inglês", "populacao":17563749, "area":118484 },
  { "nome":"Mali", "endonimo":"Mali", "iso":"ml", "capital":"Bamako", "continente":"africa", "idioma":"Francês (e bambara)", "populacao":22395489, "area":1240192 },
  { "nome":"Marrocos", "endonimo":"Al-Maghrib (المغرب) · ⵍⵎⵖⵔⵉⴱ", "iso":"ma", "capital":"Rabat", "continente":"africa", "idioma":"Árabe e berbere", "populacao":36828330, "area":446550 },
  { "nome":"Maurícia", "endonimo":"Maurice · Mauritius", "iso":"mu", "capital":"Port Louis", "continente":"africa", "idioma":"Inglês e francês", "populacao":1264613, "area":2040 },
  { "nome":"Mauritânia", "endonimo":"Mūrītāniyā (موريتانيا)", "iso":"mr", "capital":"Nuaquechote", "continente":"africa", "idioma":"Árabe", "populacao":4736139, "area":1030700 },
  { "nome":"Moçambique", "endonimo":"Moçambique", "iso":"mz", "capital":"Maputo", "continente":"africa", "idioma":"Português", "populacao":29668834, "area":801590 },
  { "nome":"Namíbia", "endonimo":"Namibia", "iso":"na", "capital":"Windhoek", "continente":"africa", "idioma":"Inglês", "populacao":2533794, "area":825615 },
  { "nome":"Níger", "endonimo":"Niger", "iso":"ne", "capital":"Niamei", "continente":"africa", "idioma":"Francês", "populacao":21477348, "area":1267000 },
  { "nome":"Nigéria", "endonimo":"Nigeria", "iso":"ng", "capital":"Abuja", "continente":"africa", "idioma":"Inglês", "populacao":211400708, "area":923768 },
  { "nome":"Quénia", "endonimo":"Kenya", "iso":"ke", "capital":"Nairóbi", "continente":"africa", "idioma":"Suaíli e inglês", "populacao":48468138, "area":581309 },
  { "nome":"República Centro-Africana", "endonimo":"Centrafrique · Ködörösêse tî Bêafrîka", "iso":"cf", "capital":"Bangui", "continente":"africa", "idioma":"Sango e francês", "populacao":5152421, "area":622984 },
  { "nome":"Ruanda", "endonimo":"Rwanda", "iso":"rw", "capital":"Kigali", "continente":"africa", "idioma":"Kinyarwanda, francês, inglês e suaíli", "populacao":14569341, "area":26338 },
  { "nome":"São Tomé e Príncipe", "endonimo":"São Tomé e Príncipe", "iso":"st", "capital":"São Tomé", "continente":"africa", "idioma":"Português", "populacao":204327, "area":1001 },
  { "nome":"Senegal", "endonimo":"Sénégal", "iso":"sn", "capital":"Dacar", "continente":"africa", "idioma":"Francês (e wolof)", "populacao":16876720, "area":196722 },
  { "nome":"Serra Leoa", "endonimo":"Sierra Leone", "iso":"sl", "capital":"Freetown", "continente":"africa", "idioma":"Inglês", "populacao":7557212, "area":71740 },
  { "nome":"Seicheles", "endonimo":"Seychelles · Sesel", "iso":"sc", "capital":"Victoria", "continente":"africa", "idioma":"Seselwa, inglês e francês", "populacao":119773, "area":459 },
  { "nome":"Somália", "endonimo":"Soomaaliya · Aṣ-Ṣūmāl", "iso":"so", "capital":"Mogadíscio", "continente":"africa", "idioma":"Somali e árabe", "populacao":11031386, "area":637657 },
  { "nome":"Sudão", "endonimo":"As-Sūdān (السودان)", "iso":"sd", "capital":"Cartum", "continente":"africa", "idioma":"Árabe e inglês", "populacao":40533330, "area":1840687 },
  { "nome":"Sudão do Sul", "endonimo":"South Sudan", "iso":"ss", "capital":"Juba", "continente":"africa", "idioma":"Inglês", "populacao":12575714, "area":644329 },
  { "nome":"Tanzânia", "endonimo":"Tanzania", "iso":"tz", "capital":"Dodoma", "continente":"africa", "idioma":"Suaíli e inglês", "populacao":57310019, "area":947303 },
  { "nome":"Togo", "endonimo":"Togo", "iso":"tg", "capital":"Lomé", "continente":"africa", "idioma":"Francês", "populacao":7797694, "area":56785 },
  { "nome":"Tunísia", "endonimo":"Tūnis (تونس)", "iso":"tn", "capital":"Túnis", "continente":"africa", "idioma":"Árabe", "populacao":11565204, "area":163610 },
  { "nome":"Uganda", "endonimo":"Uganda", "iso":"ug", "capital":"Campala", "continente":"africa", "idioma":"Inglês e suaíli", "populacao":47123531, "area":241038 },
  { "nome":"Zâmbia", "endonimo":"Zambia", "iso":"zm", "capital":"Lusaca", "continente":"africa", "idioma":"Inglês", "populacao":19610769, "area":752618 },
  { "nome":"Zimbabué", "endonimo":"Zimbabwe", "iso":"zw", "capital":"Harare", "continente":"africa", "idioma":"Inglês, shona e ndebele", "populacao":15178979, "area":390757 },
  { "nome":"Saara Ocidental", "endonimo":"Aṣ-Ṣaḥrāʾ al-Gharbiyya (الصحراء الغربية)", "iso":"eh", "capital":"Al Aiune", "continente":"africa", "soberania":"estatuto disputado", "idioma":"Árabe", "populacao":612000, "area":266000 },

  /* ===================== ÁSIA ===================== */
  { "nome":"Afeganistão", "endonimo":"Afghānistān (افغانستان)", "iso":"af", "capital":"Cabul", "continente":"asia", "idioma":"Pastó e dari", "populacao":41454761, "area":652230 },
  { "nome":"Arábia Saudita", "endonimo":"Al-ʿArabiyya as-Suʿūdiyya (السعودية)", "iso":"sa", "capital":"Riade", "continente":"asia", "idioma":"Árabe", "populacao":33000000, "area":2250000 },
  { "nome":"Arménia", "endonimo":"Hayastan (Հայաստան)", "iso":"am", "capital":"Erevan", "continente":"asia", "idioma":"Arménio", "populacao":3000000, "area":29743 },
  { "nome":"Azerbaijão", "endonimo":"Azərbaycan", "iso":"az", "capital":"Baku", "continente":"asia", "idioma":"Azeri", "populacao":10200000, "area":86600 },
  { "nome":"Bangladeche", "endonimo":"Bangladesh (বাংলাদেশ)", "iso":"bd", "capital":"Daca", "continente":"asia", "idioma":"Bengali", "populacao":171466990, "area":147570 },
  { "nome":"Barém", "endonimo":"Al-Baḥrayn (البحرين)", "iso":"bh", "capital":"Manama", "continente":"asia", "idioma":"Árabe", "populacao":1569666, "area":786 },
  { "nome":"Brunei", "endonimo":"Brunei Darussalam", "iso":"bn", "capital":"Bandar Seri Begawan", "continente":"asia", "idioma":"Malaio", "populacao":458949, "area":5765 },
  { "nome":"Butão", "endonimo":"Druk Yul (འབྲུག་ཡུལ་)", "iso":"bt", "capital":"Timphu", "continente":"asia", "idioma":"Dzongkha", "populacao":787424, "area":38394 },
  { "nome":"Camboja", "endonimo":"Kâmpuchéa (កម្ពុជា)", "iso":"kh", "capital":"Phnom Penh", "continente":"asia", "idioma":"Khmer", "populacao":17423880, "area":181035 },
  { "nome":"Catar", "endonimo":"Qaṭar (قطر)", "iso":"qa", "capital":"Doha", "continente":"asia", "idioma":"Árabe", "populacao":2639211, "area":11437 },
  { "nome":"Cazaquistão", "endonimo":"Qazaqstan (Қазақстан)", "iso":"kz", "capital":"Astana", "continente":"asia", "idioma":"Cazaque e russo", "populacao":20139914, "area":2724900 },
  { "nome":"China", "endonimo":"Zhōngguó (中国)", "iso":"cn", "capital":"Pequim", "continente":"asia", "idioma":"Chinês (mandarim)", "populacao":1404890000, "area":9596961 },
  { "nome":"Chipre", "endonimo":"Kýpros (Κύπρος) · Kıbrıs", "iso":"cy", "capital":"Nicósia", "continente":"asia", "idioma":"Grego e turco", "populacao":1340000, "area":9251 },
  { "nome":"Coreia do Norte", "endonimo":"Chosŏn (조선)", "iso":"kp", "capital":"Pyongyang", "continente":"asia", "idioma":"Coreano", "populacao":26418204, "area":120540 },
  { "nome":"Coreia do Sul", "endonimo":"Hanguk (한국)", "iso":"kr", "capital":"Seul", "continente":"asia", "idioma":"Coreano", "populacao":51466201, "area":100295 },
  { "nome":"Emirados Árabes Unidos", "endonimo":"Al-Imārāt (الإمارات)", "iso":"ae", "capital":"Abu Dhabi", "continente":"asia", "idioma":"Árabe", "populacao":9890400, "area":83600 },
  { "nome":"Filipinas", "endonimo":"Pilipinas", "iso":"ph", "capital":"Manila", "continente":"asia", "idioma":"Filipino e inglês", "populacao":112729484, "area":343448 },
  { "nome":"Geórgia", "endonimo":"Sakartvelo (საქართველო)", "iso":"ge", "capital":"Tbilisi", "continente":"asia", "idioma":"Georgiano", "populacao":3700000, "area":69700 },
  { "nome":"Iémen", "endonimo":"Al-Yaman (اليمن)", "iso":"ye", "capital":"Sana", "continente":"asia", "idioma":"Árabe", "populacao":28250420, "area":455503 },
  { "nome":"Índia", "endonimo":"Bhārat (भारत) · India", "iso":"in", "capital":"Nova Deli", "continente":"asia", "idioma":"Hindi, inglês (e mais 21)", "populacao":1326093247, "area":3287263 },
  { "nome":"Indonésia", "endonimo":"Indonesia", "iso":"id", "capital":"Jacarta", "continente":"asia", "idioma":"Indonésio", "populacao":275439000, "area":1904570 },
  { "nome":"Irão", "endonimo":"Īrān (ایران)", "iso":"ir", "capital":"Teerão", "continente":"asia", "idioma":"Persa (farsi)", "populacao":92417700, "area":1648195 },
  { "nome":"Iraque", "endonimo":"Al-ʿIrāq (العراق) · Êraq", "iso":"iq", "capital":"Bagdade", "continente":"asia", "idioma":"Árabe e curdo", "populacao":38274618, "area":437072 },
  { "nome":"Israel", "endonimo":"Yisra'el (ישראל) · Isrāʼīl", "iso":"il", "capital":"Jerusalém", "continente":"asia", "idioma":"Hebraico (e árabe)", "populacao":9840000, "area":20770 },
  { "nome":"Japão", "endonimo":"Nihon · Nippon (日本)", "iso":"jp", "capital":"Tóquio", "continente":"asia", "idioma":"Japonês", "populacao":123802000, "area":377972 },
  { "nome":"Jordânia", "endonimo":"Al-Urdunn (الأردن)", "iso":"jo", "capital":"Amã", "continente":"asia", "idioma":"Árabe", "populacao":10428241, "area":89341 },
  { "nome":"Koweit", "endonimo":"Al-Kuwayt (الكويت)", "iso":"kw", "capital":"Cidade do Koweit", "continente":"asia", "idioma":"Árabe", "populacao":4464000, "area":17818 },
  { "nome":"Laos", "endonimo":"Lāo (ລາວ)", "iso":"la", "capital":"Vienciana", "continente":"asia", "idioma":"Lao", "populacao":6858160, "area":236800 },
  { "nome":"Líbano", "endonimo":"Lubnān (لبنان)", "iso":"lb", "capital":"Beirute", "continente":"asia", "idioma":"Árabe", "populacao":6100075, "area":10452 },
  { "nome":"Malásia", "endonimo":"Malaysia", "iso":"my", "capital":"Kuala Lumpur", "continente":"asia", "idioma":"Malaio", "populacao":34231700, "area":330803 },
  { "nome":"Maldivas", "endonimo":"Dhivehi Raajje (ދިވެހިރާއްޖެ)", "iso":"mv", "capital":"Malé", "continente":"asia", "idioma":"Divehi", "populacao":436330, "area":298 },
  { "nome":"Mongólia", "endonimo":"Mongol Uls (Монгол Улс)", "iso":"mn", "capital":"Ulã Bator", "continente":"asia", "idioma":"Mongol", "populacao":3409939, "area":1564116 },
  { "nome":"Myanmar", "endonimo":"Myanma (မြန်မာ)", "iso":"mm", "capital":"Nay Pyi Taw", "continente":"asia", "idioma":"Birmanês", "populacao":53370609, "area":676577 },
  { "nome":"Nepal", "endonimo":"Nepāl (नेपाल)", "iso":"np", "capital":"Catmandu", "continente":"asia", "idioma":"Nepali", "populacao":29164578, "area":147181 },
  { "nome":"Omã", "endonimo":"ʿUmān (عُمان)", "iso":"om", "capital":"Mascate", "continente":"asia", "idioma":"Árabe", "populacao":4829480, "area":309500 },
  { "nome":"Paquistão", "endonimo":"Pākistān (پاکستان)", "iso":"pk", "capital":"Islamabade", "continente":"asia", "idioma":"Urdu e inglês", "populacao":223773700, "area":881913 },
  { "nome":"Palestina", "endonimo":"Filasṭīn (فلسطين)", "iso":"ps", "capital":"Ramala · Jerusalém Oriental", "continente":"asia", "idioma":"Árabe", "populacao":5227193, "area":6020 },
  { "nome":"Quirguistão", "endonimo":"Kyrgyzstan (Кыргызстан)", "iso":"kg", "capital":"Bisqueque", "continente":"asia", "idioma":"Quirguiz e russo", "populacao":7281800, "area":199951 },
  { "nome":"Singapura", "endonimo":"Singapore · Singapura · 新加坡 · சிங்கப்பூர்", "iso":"sg", "capital":"Singapura", "continente":"asia", "idioma":"Inglês, malaio, mandarim, tâmil", "populacao":5866139, "area":719 },
  { "nome":"Síria", "endonimo":"Sūriyā (سوريا)", "iso":"sy", "capital":"Damasco", "continente":"asia", "idioma":"Árabe", "populacao":23865423, "area":185180 },
  { "nome":"Sri Lanka", "endonimo":"Sri Laṃkā (ශ්‍රී ලංකා · இலங்கை)", "iso":"lk", "capital":"Sri Jayawardenepura Kotte", "continente":"asia", "idioma":"Cingalês e tâmil", "populacao":21444000, "area":65610 },
  { "nome":"Tailândia", "endonimo":"Prathet Thai (ประเทศไทย)", "iso":"th", "capital":"Banguecoque", "continente":"asia", "idioma":"Tailandês", "populacao":66188503, "area":513120 },
  { "nome":"Tajiquistão", "endonimo":"Tojikiston (Тоҷикистон)", "iso":"tj", "capital":"Duchambé", "continente":"asia", "idioma":"Tajique", "populacao":9504000, "area":143100 },
  { "nome":"Timor-Leste", "endonimo":"Timór Lorosa'e · Timor-Leste", "iso":"tl", "capital":"Díli", "continente":"asia", "idioma":"Tétum e português", "populacao":1400638, "area":14919 },
  { "nome":"Turquemenistão", "endonimo":"Türkmenistan", "iso":"tm", "capital":"Asgabate", "continente":"asia", "idioma":"Turcomano", "populacao":6117933, "area":491210 },
  { "nome":"Turquia", "endonimo":"Türkiye", "iso":"tr", "capital":"Ancara", "continente":"asia", "idioma":"Turco", "populacao":85300000, "area":783562 },
  { "nome":"Usbequistão", "endonimo":"Oʻzbekiston", "iso":"uz", "capital":"Tasquente", "continente":"asia", "idioma":"Usbeque", "populacao":34915100, "area":448978 },
  { "nome":"Vietname", "endonimo":"Việt Nam", "iso":"vn", "capital":"Hanói", "continente":"asia", "idioma":"Vietnamita", "populacao":96208984, "area":331690 },
  { "nome":"Taiwan", "endonimo":"Táiwān (臺灣) · Zhōnghuá Mínguó", "iso":"tw", "capital":"Taipé", "continente":"asia", "soberania":"estatuto disputado", "idioma":"Chinês (mandarim)", "populacao":23317031, "area":36193 },
  { "nome":"Hong Kong", "endonimo":"Hēunggóng (香港)", "iso":"hk", "capital":"—", "continente":"asia", "soberania":"China", "idioma":"Cantonês e inglês", "populacao":7413070, "area":1106 },
  { "nome":"Macau", "endonimo":"Macau · Ou Mun (澳門)", "iso":"mo", "capital":"—", "continente":"asia", "soberania":"China", "idioma":"Cantonês e português", "populacao":682100, "area":115 },

  /* ===================== AMÉRICA ===================== */
  { "nome":"Antígua e Barbuda", "endonimo":"Antigua and Barbuda", "iso":"ag", "capital":"Saint John's", "continente":"america", "idioma":"Inglês", "populacao":101489, "area":440 },
  { "nome":"Argentina", "endonimo":"Argentina", "iso":"ar", "capital":"Buenos Aires", "continente":"america", "idioma":"Espanhol", "populacao":47327407, "area":2780400 },
  { "nome":"Baamas", "endonimo":"The Bahamas", "iso":"bs", "capital":"Nassau", "continente":"america", "idioma":"Inglês", "populacao":399440, "area":13878 },
  { "nome":"Barbados", "endonimo":"Barbados", "iso":"bb", "capital":"Bridgetown", "continente":"america", "idioma":"Inglês", "populacao":303431, "area":439 },
  { "nome":"Belize", "endonimo":"Belize", "iso":"bz", "capital":"Belmopan", "continente":"america", "idioma":"Inglês", "populacao":411106, "area":22966 },
  { "nome":"Bolívia", "endonimo":"Bolivia · Wuliwya · Buliwya", "iso":"bo", "capital":"Sucre", "continente":"america", "idioma":"Espanhol, quíchua e aimará", "populacao":12244159, "area":1098581 },
  { "nome":"Brasil", "endonimo":"Brasil", "iso":"br", "capital":"Brasília", "continente":"america", "idioma":"Português", "populacao":214211951, "area":8515767 },
  { "nome":"Canadá", "endonimo":"Canada", "iso":"ca", "capital":"Otava", "continente":"america", "idioma":"Inglês e francês", "populacao":36991981, "area":9984670 },
  { "nome":"Chile", "endonimo":"Chile", "iso":"cl", "capital":"Santiago", "continente":"america", "idioma":"Espanhol", "populacao":19458000, "area":756102 },
  { "nome":"Colômbia", "endonimo":"Colombia", "iso":"co", "capital":"Bogotá", "continente":"america", "idioma":"Espanhol", "populacao":52321152, "area":1141748 },
  { "nome":"Costa Rica", "endonimo":"Costa Rica", "iso":"cr", "capital":"São José", "continente":"america", "idioma":"Espanhol", "populacao":5265575, "area":51180 },
  { "nome":"Cuba", "endonimo":"Cuba", "iso":"cu", "capital":"Havana", "continente":"america", "idioma":"Espanhol", "populacao":10985974, "area":109884 },
  { "nome":"Domínica", "endonimo":"Dominica", "iso":"dm", "capital":"Roseau", "continente":"america", "idioma":"Inglês", "populacao":74656, "area":751 },
  { "nome":"El Salvador", "endonimo":"El Salvador", "iso":"sv", "capital":"São Salvador", "continente":"america", "idioma":"Espanhol", "populacao":6029976, "area":21041 },
  { "nome":"Equador", "endonimo":"Ecuador", "iso":"ec", "capital":"Quito", "continente":"america", "idioma":"Espanhol", "populacao":16938986, "area":257204 },
  { "nome":"Estados Unidos", "endonimo":"United States", "iso":"us", "capital":"Washington, D.C.", "continente":"america", "idioma":"Inglês (de facto)", "populacao":340110988, "area":9826675 },
  { "nome":"Granada", "endonimo":"Grenada", "iso":"gd", "capital":"Saint George's", "continente":"america", "idioma":"Inglês", "populacao":114299, "area":348 },
  { "nome":"Guatemala", "endonimo":"Guatemala", "iso":"gt", "capital":"Cidade da Guatemala", "continente":"america", "idioma":"Espanhol", "populacao":17263239, "area":108889 },
  { "nome":"Guiana", "endonimo":"Guyana", "iso":"gy", "capital":"Georgetown", "continente":"america", "idioma":"Inglês", "populacao":878674, "area":214970 },
  { "nome":"Haiti", "endonimo":"Haïti · Ayiti", "iso":"ht", "capital":"Porto Príncipe", "continente":"america", "idioma":"Crioulo haitiano e francês", "populacao":10981229, "area":27750 },
  { "nome":"Honduras", "endonimo":"Honduras", "iso":"hn", "capital":"Tegucigalpa", "continente":"america", "idioma":"Espanhol", "populacao":8303771, "area":112492 },
  { "nome":"Jamaica", "endonimo":"Jamaica", "iso":"jm", "capital":"Kingston", "continente":"america", "idioma":"Inglês", "populacao":2697983, "area":10992 },
  { "nome":"México", "endonimo":"México", "iso":"mx", "capital":"Cidade do México", "continente":"america", "idioma":"Espanhol", "populacao":132274416, "area":1964375 },
  { "nome":"Nicarágua", "endonimo":"Nicaragua", "iso":"ni", "capital":"Manágua", "continente":"america", "idioma":"Espanhol", "populacao":5142098, "area":120340 },
  { "nome":"Panamá", "endonimo":"Panamá", "iso":"pa", "capital":"Cidade do Panamá", "continente":"america", "idioma":"Espanhol", "populacao":4570133, "area":74177 },
  { "nome":"Paraguai", "endonimo":"Paraguay · Paraguái", "iso":"py", "capital":"Assunção", "continente":"america", "idioma":"Espanhol e guarani", "populacao":6811297, "area":406756 },
  { "nome":"Peru", "endonimo":"Perú · Piruw", "iso":"pe", "capital":"Lima", "continente":"america", "idioma":"Espanhol e quíchua", "populacao":34157732, "area":1285216 },
  { "nome":"República Dominicana", "endonimo":"República Dominicana", "iso":"do", "capital":"São Domingos", "continente":"america", "idioma":"Espanhol", "populacao":10760028, "area":48671 },
  { "nome":"Santa Lúcia", "endonimo":"Saint Lucia", "iso":"lc", "capital":"Castries", "continente":"america", "idioma":"Inglês", "populacao":167591, "area":617 },
  { "nome":"São Cristóvão e Neves", "endonimo":"Saint Kitts and Nevis", "iso":"kn", "capital":"Basseterre", "continente":"america", "idioma":"Inglês", "populacao":46922, "area":269 },
  { "nome":"São Vicente e Granadinas", "endonimo":"Saint Vincent and the Grenadines", "iso":"vc", "capital":"Kingstown", "continente":"america", "idioma":"Inglês", "populacao":109897, "area":389 },
  { "nome":"Suriname", "endonimo":"Suriname", "iso":"sr", "capital":"Paramaribo", "continente":"america", "idioma":"Neerlandês", "populacao":563402, "area":163270 },
  { "nome":"Trindade e Tobago", "endonimo":"Trinidad and Tobago", "iso":"tt", "capital":"Port of Spain", "continente":"america", "idioma":"Inglês", "populacao":1369125, "area":5128 },
  { "nome":"Uruguai", "endonimo":"Uruguay", "iso":"uy", "capital":"Montevideu", "continente":"america", "idioma":"Espanhol", "populacao":3444263, "area":176215 },
  { "nome":"Venezuela", "endonimo":"Venezuela", "iso":"ve", "capital":"Caracas", "continente":"america", "idioma":"Espanhol", "populacao":31250306, "area":912050 },
  { "nome":"Gronelândia", "endonimo":"Kalaallit Nunaat · Grønland", "iso":"gl", "capital":"Nuuk", "continente":"america", "soberania":"Dinamarca", "idioma":"Gronelandês e dinamarquês", "populacao":56609, "area":2166086 },
  { "nome":"Porto Rico", "endonimo":"Puerto Rico", "iso":"pr", "capital":"San Juan", "continente":"america", "soberania":"Estados Unidos", "idioma":"Espanhol e inglês", "populacao":3285874, "area":9104 },
  { "nome":"Bermudas", "endonimo":"Bermuda", "iso":"bm", "capital":"Hamilton", "continente":"america", "soberania":"Reino Unido", "idioma":"Inglês", "populacao":65024, "area":53 },
  { "nome":"Aruba", "endonimo":"Aruba", "iso":"aw", "capital":"Oranjestad", "continente":"america", "soberania":"Países Baixos", "idioma":"Neerlandês e papiamento", "populacao":106739, "area":179 },
  { "nome":"Curaçao", "endonimo":"Curaçao · Kòrsou", "iso":"cw", "capital":"Willemstad", "continente":"america", "soberania":"Países Baixos", "idioma":"Neerlandês e papiamento", "populacao":152849, "area":444 },
  { "nome":"Ilhas Caimão", "endonimo":"Cayman Islands", "iso":"ky", "capital":"George Town", "continente":"america", "soberania":"Reino Unido", "idioma":"Inglês", "populacao":88833, "area":264 },

  /* ===================== OCEÂNIA ===================== */
  { "nome":"Austrália", "endonimo":"Australia", "iso":"au", "capital":"Camberra", "continente":"oceania", "idioma":"Inglês (de facto)", "populacao":27614411, "area":7692024 },
  { "nome":"Fiji", "endonimo":"Viti · Fiji · Fijī", "iso":"fj", "capital":"Suva", "continente":"oceania", "idioma":"Inglês, fijiano e hindustani", "populacao":926276, "area":18274 },
  { "nome":"Ilhas Marshall", "endonimo":"Aolepān Aorōkin M̧ajeḷ", "iso":"mh", "capital":"Majuro", "continente":"oceania", "idioma":"Marshalês e inglês", "populacao":53127, "area":181 },
  { "nome":"Ilhas Salomão", "endonimo":"Solomon Islands", "iso":"sb", "capital":"Honiara", "continente":"oceania", "idioma":"Inglês", "populacao":611343, "area":28400 },
  { "nome":"Kiribati", "endonimo":"Kiribati", "iso":"ki", "capital":"Tarawa Sul", "continente":"oceania", "idioma":"Kiribati e inglês", "populacao":134518, "area":811 },
  { "nome":"Micronésia", "endonimo":"Micronesia", "iso":"fm", "capital":"Palikir", "continente":"oceania", "idioma":"Inglês", "populacao":75817, "area":702 },
  { "nome":"Nauru", "endonimo":"Naoero · Nauru", "iso":"nr", "capital":"Iaren", "continente":"oceania", "idioma":"Nauruano e inglês", "populacao":13650, "area":21 },
  { "nome":"Nova Zelândia", "endonimo":"New Zealand · Aotearoa", "iso":"nz", "capital":"Wellington", "continente":"oceania", "idioma":"Inglês, maori e língua gestual", "populacao":5307800, "area":268021 },
  { "nome":"Palau", "endonimo":"Belau · Palau", "iso":"pw", "capital":"Ngerulmud", "continente":"oceania", "idioma":"Palauano e inglês", "populacao":21729, "area":466 },
  { "nome":"Papua-Nova Guiné", "endonimo":"Papua Niugini · Papua New Guinea", "iso":"pg", "capital":"Port Moresby", "continente":"oceania", "idioma":"Tok pisin, inglês, hiri motu", "populacao":8935000, "area":462840 },
  { "nome":"Samoa", "endonimo":"Sāmoa", "iso":"ws", "capital":"Apia", "continente":"oceania", "idioma":"Samoano e inglês", "populacao":200010, "area":2842 },
  { "nome":"Tonga", "endonimo":"Tonga", "iso":"to", "capital":"Nucualofa", "continente":"oceania", "idioma":"Tonganês e inglês", "populacao":108020, "area":749 },
  { "nome":"Tuvalu", "endonimo":"Tuvalu", "iso":"tv", "capital":"Funafuti", "continente":"oceania", "idioma":"Tuvaluano e inglês", "populacao":10643, "area":25 },
  { "nome":"Vanuatu", "endonimo":"Vanuatu", "iso":"vu", "capital":"Port Vila", "continente":"oceania", "idioma":"Bislama, inglês e francês", "populacao":300019, "area":12190 },
  { "nome":"Polinésia Francesa", "endonimo":"Polynésie française · Pōrīnetia Farāni", "iso":"pf", "capital":"Papeete", "continente":"oceania", "soberania":"França", "idioma":"Francês", "populacao":278786, "area":4167 },
  { "nome":"Nova Caledónia", "endonimo":"Nouvelle-Calédonie", "iso":"nc", "capital":"Nouméa", "continente":"oceania", "soberania":"França", "idioma":"Francês", "populacao":278500, "area":18576 },
  { "nome":"Guam", "endonimo":"Guåhan · Guam", "iso":"gu", "capital":"Hagåtña", "continente":"oceania", "soberania":"Estados Unidos", "idioma":"Inglês e chamorro", "populacao":153836, "area":544 },
  { "nome":"Ilhas Cook", "endonimo":"Kūki 'Āirani · Cook Islands", "iso":"ck", "capital":"Avarua", "continente":"oceania", "soberania":"Nova Zelândia (assoc. livre)", "idioma":"Inglês e maori cook", "populacao":14222, "area":240 }

];
