/* =========================================================================
   DADOS DOS PAÍSES  —  "O Mundo, Continente a Continente"
   -------------------------------------------------------------------------
   Lista JSON dentro de uma variável (window.PAISES). A única diferença para
   um .json puro é a linha de atribuição no início — assim o livro abre
   directamente do disco (file://), sem servidor web.

   Cada entrada:
     nome        nome em português
     endonimo    nome na(s) língua(s) oficial(is) (romanização + grafia nativa)
     iso         código de 2 letras, minúsculas (bandeira + mapa)
     capital     capital (ou sede de governo)
     continente  africa | america | asia | europa | oceania
     soberania   (só territórios) Estado a que pertence

   - Estados soberanos + alguns territórios com bandeira própria.
   - A ORDEM dentro de cada continente é alfabética (livro de consulta).
   - A ordem dos continentes no livro é definida em livro-planisfério.html.
   ========================================================================= */
window.PAISES = [

  /* ===================== EUROPA ===================== */
  { "nome":"Albânia", "endonimo":"Shqipëria", "iso":"al", "capital":"Tirana", "continente":"europa", "idioma":"Albanês" },
  { "nome":"Alemanha", "endonimo":"Deutschland", "iso":"de", "capital":"Berlim", "continente":"europa", "idioma":"Alemão" },
  { "nome":"Andorra", "endonimo":"Andorra", "iso":"ad", "capital":"Andorra-a-Velha", "continente":"europa", "idioma":"Catalão" },
  { "nome":"Áustria", "endonimo":"Österreich", "iso":"at", "capital":"Viena", "continente":"europa", "idioma":"Alemão" },
  { "nome":"Bélgica", "endonimo":"België · Belgique · Belgien", "iso":"be", "capital":"Bruxelas", "continente":"europa", "idioma":"Neerlandês, francês e alemão" },
  { "nome":"Bielorrússia", "endonimo":"Bielarus (Беларусь)", "iso":"by", "capital":"Minsk", "continente":"europa", "idioma":"Bielorrusso e russo" },
  { "nome":"Bósnia e Herzegovina", "endonimo":"Bosna i Hercegovina (Босна и Херцеговина)", "iso":"ba", "capital":"Sarajevo", "continente":"europa", "idioma":"Bósnio, croata e sérvio" },
  { "nome":"Bulgária", "endonimo":"Balgariya (България)", "iso":"bg", "capital":"Sófia", "continente":"europa", "idioma":"Búlgaro" },
  { "nome":"Chéquia", "endonimo":"Česko", "iso":"cz", "capital":"Praga", "continente":"europa", "idioma":"Checo" },
  { "nome":"Cidade do Vaticano", "endonimo":"Città del Vaticano", "iso":"va", "capital":"Vaticano", "continente":"europa", "idioma":"Italiano (latim, na Santa Sé)" },
  { "nome":"Croácia", "endonimo":"Hrvatska", "iso":"hr", "capital":"Zagrebe", "continente":"europa", "idioma":"Croata" },
  { "nome":"Dinamarca", "endonimo":"Danmark", "iso":"dk", "capital":"Copenhaga", "continente":"europa", "idioma":"Dinamarquês" },
  { "nome":"Eslováquia", "endonimo":"Slovensko", "iso":"sk", "capital":"Bratislava", "continente":"europa", "idioma":"Eslovaco" },
  { "nome":"Eslovénia", "endonimo":"Slovenija", "iso":"si", "capital":"Liubliana", "continente":"europa", "idioma":"Esloveno" },
  { "nome":"Espanha", "endonimo":"España", "iso":"es", "capital":"Madrid", "continente":"europa", "idioma":"Espanhol" },
  { "nome":"Estónia", "endonimo":"Eesti", "iso":"ee", "capital":"Taline", "continente":"europa", "idioma":"Estónio" },
  { "nome":"Finlândia", "endonimo":"Suomi · Finland", "iso":"fi", "capital":"Helsínquia", "continente":"europa", "idioma":"Finlandês e sueco" },
  { "nome":"França", "endonimo":"France", "iso":"fr", "capital":"Paris", "continente":"europa", "idioma":"Francês" },
  { "nome":"Grécia", "endonimo":"Elláda (Ελλάδα)", "iso":"gr", "capital":"Atenas", "continente":"europa", "idioma":"Grego" },
  { "nome":"Hungria", "endonimo":"Magyarország", "iso":"hu", "capital":"Budapeste", "continente":"europa", "idioma":"Húngaro" },
  { "nome":"Irlanda", "endonimo":"Éire · Ireland", "iso":"ie", "capital":"Dublin", "continente":"europa", "idioma":"Irlandês e inglês" },
  { "nome":"Islândia", "endonimo":"Ísland", "iso":"is", "capital":"Reiquiavique", "continente":"europa", "idioma":"Islandês" },
  { "nome":"Itália", "endonimo":"Italia", "iso":"it", "capital":"Roma", "continente":"europa", "idioma":"Italiano" },
  { "nome":"Kosovo", "endonimo":"Kosova · Kosovo", "iso":"xk", "capital":"Pristina", "continente":"europa", "idioma":"Albanês e sérvio" },
  { "nome":"Letónia", "endonimo":"Latvija", "iso":"lv", "capital":"Riga", "continente":"europa", "idioma":"Letão" },
  { "nome":"Listenstaine", "endonimo":"Liechtenstein", "iso":"li", "capital":"Vaduz", "continente":"europa", "idioma":"Alemão" },
  { "nome":"Lituânia", "endonimo":"Lietuva", "iso":"lt", "capital":"Vílnius", "continente":"europa", "idioma":"Lituano" },
  { "nome":"Luxemburgo", "endonimo":"Lëtzebuerg · Luxembourg · Luxemburg", "iso":"lu", "capital":"Luxemburgo", "continente":"europa", "idioma":"Luxemburguês, francês e alemão" },
  { "nome":"Macedónia do Norte", "endonimo":"Severna Makedonija (Северна Македонија)", "iso":"mk", "capital":"Escópia", "continente":"europa", "idioma":"Macedónio" },
  { "nome":"Malta", "endonimo":"Malta", "iso":"mt", "capital":"Valeta", "continente":"europa", "idioma":"Maltês e inglês" },
  { "nome":"Moldávia", "endonimo":"Moldova", "iso":"md", "capital":"Chișinău", "continente":"europa", "idioma":"Romeno" },
  { "nome":"Mónaco", "endonimo":"Monaco", "iso":"mc", "capital":"Mónaco", "continente":"europa", "idioma":"Francês" },
  { "nome":"Montenegro", "endonimo":"Crna Gora (Црна Гора)", "iso":"me", "capital":"Podgorica", "continente":"europa", "idioma":"Montenegrino" },
  { "nome":"Noruega", "endonimo":"Norge · Noreg", "iso":"no", "capital":"Oslo", "continente":"europa", "idioma":"Norueguês" },
  { "nome":"Países Baixos", "endonimo":"Nederland", "iso":"nl", "capital":"Amesterdão", "continente":"europa", "idioma":"Neerlandês" },
  { "nome":"Polónia", "endonimo":"Polska", "iso":"pl", "capital":"Varsóvia", "continente":"europa", "idioma":"Polaco" },
  { "nome":"Portugal", "endonimo":"Portugal", "iso":"pt", "capital":"Lisboa", "continente":"europa", "idioma":"Português" },
  { "nome":"Reino Unido", "endonimo":"United Kingdom", "iso":"gb", "capital":"Londres", "continente":"europa", "idioma":"Inglês" },
  { "nome":"Roménia", "endonimo":"România", "iso":"ro", "capital":"Bucareste", "continente":"europa", "idioma":"Romeno" },
  { "nome":"Rússia", "endonimo":"Rossiya (Россия)", "iso":"ru", "capital":"Moscovo", "continente":"europa", "idioma":"Russo" },
  { "nome":"San Marino", "endonimo":"San Marino", "iso":"sm", "capital":"Cidade de San Marino", "continente":"europa", "idioma":"Italiano" },
  { "nome":"Sérvia", "endonimo":"Srbija (Србија)", "iso":"rs", "capital":"Belgrado", "continente":"europa", "idioma":"Sérvio" },
  { "nome":"Suécia", "endonimo":"Sverige", "iso":"se", "capital":"Estocolmo", "continente":"europa", "idioma":"Sueco" },
  { "nome":"Suíça", "endonimo":"Schweiz · Suisse · Svizzera · Svizra", "iso":"ch", "capital":"Berna", "continente":"europa", "idioma":"Alemão, francês, italiano e romanche" },
  { "nome":"Ucrânia", "endonimo":"Ukraïna (Україна)", "iso":"ua", "capital":"Kiev", "continente":"europa", "idioma":"Ucraniano" },
  { "nome":"Ilhas Faroé", "endonimo":"Føroyar", "iso":"fo", "capital":"Tórshavn", "continente":"europa", "soberania":"Dinamarca", "idioma":"Feroês e dinamarquês" },
  { "nome":"Gibraltar", "endonimo":"Gibraltar", "iso":"gi", "capital":"Gibraltar", "continente":"europa", "soberania":"Reino Unido", "idioma":"Inglês" },
  { "nome":"Ilha de Man", "endonimo":"Mannin · Isle of Man", "iso":"im", "capital":"Douglas", "continente":"europa", "soberania":"Coroa britânica", "idioma":"Inglês (e manquês)" },
  { "nome":"Jersey", "endonimo":"Jersey · Jèrri", "iso":"je", "capital":"Saint Helier", "continente":"europa", "soberania":"Coroa britânica", "idioma":"Inglês e francês" },
  { "nome":"Guernsey", "endonimo":"Guernsey · Guernési", "iso":"gg", "capital":"St. Peter Port", "continente":"europa", "soberania":"Coroa britânica", "idioma":"Inglês e francês" },
  { "nome":"Alanda", "endonimo":"Åland", "iso":"ax", "capital":"Mariehamn", "continente":"europa", "soberania":"Finlândia", "idioma":"Sueco" },

  /* ===================== ÁFRICA ===================== */
  { "nome":"África do Sul", "endonimo":"South Africa · Suid-Afrika · iNingizimu Afrika", "iso":"za", "capital":"Pretória · Cidade do Cabo · Bloemfontein", "continente":"africa", "idioma":"11 línguas (inglês, zulu, xhosa…)" },
  { "nome":"Angola", "endonimo":"Angola", "iso":"ao", "capital":"Luanda", "continente":"africa", "idioma":"Português" },
  { "nome":"Argélia", "endonimo":"Al-Jazair (الجزائر)", "iso":"dz", "capital":"Argel", "continente":"africa", "idioma":"Árabe e berbere" },
  { "nome":"Benim", "endonimo":"Bénin", "iso":"bj", "capital":"Porto-Novo", "continente":"africa", "idioma":"Francês" },
  { "nome":"Botsuana", "endonimo":"Botswana", "iso":"bw", "capital":"Gaborone", "continente":"africa", "idioma":"Inglês e tswana" },
  { "nome":"Burquina Faso", "endonimo":"Burkina Faso", "iso":"bf", "capital":"Uagadugu", "continente":"africa", "idioma":"Francês" },
  { "nome":"Burúndi", "endonimo":"Uburundi · Burundi", "iso":"bi", "capital":"Gitega", "continente":"africa", "idioma":"Kirundi e francês" },
  { "nome":"Cabo Verde", "endonimo":"Cabo Verde", "iso":"cv", "capital":"Praia", "continente":"africa", "idioma":"Português (e crioulo cabo-verdiano)" },
  { "nome":"Camarões", "endonimo":"Cameroun · Cameroon", "iso":"cm", "capital":"Iaundé", "continente":"africa", "idioma":"Francês e inglês" },
  { "nome":"Chade", "endonimo":"Tchad · Tšād", "iso":"td", "capital":"Jamena", "continente":"africa", "idioma":"Árabe e francês" },
  { "nome":"Comores", "endonimo":"Komori · Juzur al-Qamar", "iso":"km", "capital":"Moroni", "continente":"africa", "idioma":"Comoriano, árabe e francês" },
  { "nome":"Congo", "endonimo":"Congo", "iso":"cg", "capital":"Brazzaville", "continente":"africa", "idioma":"Francês" },
  { "nome":"Congo (República Democrática)", "endonimo":"Congo", "iso":"cd", "capital":"Kinshasa", "continente":"africa", "idioma":"Francês" },
  { "nome":"Costa do Marfim", "endonimo":"Côte d'Ivoire", "iso":"ci", "capital":"Yamoussoukro", "continente":"africa", "idioma":"Francês" },
  { "nome":"Egito", "endonimo":"Misr (مصر)", "iso":"eg", "capital":"Cairo", "continente":"africa", "idioma":"Árabe" },
  { "nome":"Eritreia", "endonimo":"Ertra (ኤርትራ) · Iritriyā", "iso":"er", "capital":"Asmara", "continente":"africa", "idioma":"Tigrínia, árabe e inglês" },
  { "nome":"Essuatíni", "endonimo":"eSwatini", "iso":"sz", "capital":"Mbabane", "continente":"africa", "idioma":"Suázi e inglês" },
  { "nome":"Etiópia", "endonimo":"Ītyōṗṗyā (ኢትዮጵያ)", "iso":"et", "capital":"Adis Abeba", "continente":"africa", "idioma":"Amárico" },
  { "nome":"Gabão", "endonimo":"Gabon", "iso":"ga", "capital":"Libreville", "continente":"africa", "idioma":"Francês" },
  { "nome":"Gâmbia", "endonimo":"The Gambia", "iso":"gm", "capital":"Banjul", "continente":"africa", "idioma":"Inglês" },
  { "nome":"Gana", "endonimo":"Ghana", "iso":"gh", "capital":"Acra", "continente":"africa", "idioma":"Inglês" },
  { "nome":"Guiné", "endonimo":"Guinée", "iso":"gn", "capital":"Conacri", "continente":"africa", "idioma":"Francês" },
  { "nome":"Guiné-Bissau", "endonimo":"Guiné-Bissau", "iso":"gw", "capital":"Bissau", "continente":"africa", "idioma":"Português (e crioulo)" },
  { "nome":"Guiné Equatorial", "endonimo":"Guinea Ecuatorial · Guinée équatoriale", "iso":"gq", "capital":"Malabo", "continente":"africa", "idioma":"Espanhol, francês e português" },
  { "nome":"Jibuti", "endonimo":"Jībūtī · Gabuuti", "iso":"dj", "capital":"Jibuti", "continente":"africa", "idioma":"Árabe e francês" },
  { "nome":"Lesoto", "endonimo":"Lesotho", "iso":"ls", "capital":"Maseru", "continente":"africa", "idioma":"Sesoto e inglês" },
  { "nome":"Libéria", "endonimo":"Liberia", "iso":"lr", "capital":"Monróvia", "continente":"africa", "idioma":"Inglês" },
  { "nome":"Líbia", "endonimo":"Lībiyā (ليبيا)", "iso":"ly", "capital":"Trípoli", "continente":"africa", "idioma":"Árabe" },
  { "nome":"Madagáscar", "endonimo":"Madagasikara · Madagascar", "iso":"mg", "capital":"Antananarivo", "continente":"africa", "idioma":"Malgaxe e francês" },
  { "nome":"Malávi", "endonimo":"Malaŵi", "iso":"mw", "capital":"Lilongwe", "continente":"africa", "idioma":"Chicheua e inglês" },
  { "nome":"Mali", "endonimo":"Mali", "iso":"ml", "capital":"Bamako", "continente":"africa", "idioma":"Francês (e bambara)" },
  { "nome":"Marrocos", "endonimo":"Al-Maghrib (المغرب) · ⵍⵎⵖⵔⵉⴱ", "iso":"ma", "capital":"Rabat", "continente":"africa", "idioma":"Árabe e berbere" },
  { "nome":"Maurícia", "endonimo":"Maurice · Mauritius", "iso":"mu", "capital":"Port Louis", "continente":"africa", "idioma":"Inglês e francês" },
  { "nome":"Mauritânia", "endonimo":"Mūrītāniyā (موريتانيا)", "iso":"mr", "capital":"Nuaquechote", "continente":"africa", "idioma":"Árabe" },
  { "nome":"Moçambique", "endonimo":"Moçambique", "iso":"mz", "capital":"Maputo", "continente":"africa", "idioma":"Português" },
  { "nome":"Namíbia", "endonimo":"Namibia", "iso":"na", "capital":"Windhoek", "continente":"africa", "idioma":"Inglês" },
  { "nome":"Níger", "endonimo":"Niger", "iso":"ne", "capital":"Niamei", "continente":"africa", "idioma":"Francês" },
  { "nome":"Nigéria", "endonimo":"Nigeria", "iso":"ng", "capital":"Abuja", "continente":"africa", "idioma":"Inglês" },
  { "nome":"Quénia", "endonimo":"Kenya", "iso":"ke", "capital":"Nairóbi", "continente":"africa", "idioma":"Suaíli e inglês" },
  { "nome":"República Centro-Africana", "endonimo":"Centrafrique · Ködörösêse tî Bêafrîka", "iso":"cf", "capital":"Bangui", "continente":"africa", "idioma":"Sango e francês" },
  { "nome":"Ruanda", "endonimo":"Rwanda", "iso":"rw", "capital":"Kigali", "continente":"africa", "idioma":"Kinyarwanda, francês, inglês e suaíli" },
  { "nome":"São Tomé e Príncipe", "endonimo":"São Tomé e Príncipe", "iso":"st", "capital":"São Tomé", "continente":"africa", "idioma":"Português" },
  { "nome":"Senegal", "endonimo":"Sénégal", "iso":"sn", "capital":"Dacar", "continente":"africa", "idioma":"Francês (e wolof)" },
  { "nome":"Serra Leoa", "endonimo":"Sierra Leone", "iso":"sl", "capital":"Freetown", "continente":"africa", "idioma":"Inglês" },
  { "nome":"Seicheles", "endonimo":"Seychelles · Sesel", "iso":"sc", "capital":"Victoria", "continente":"africa", "idioma":"Seselwa, inglês e francês" },
  { "nome":"Somália", "endonimo":"Soomaaliya · Aṣ-Ṣūmāl", "iso":"so", "capital":"Mogadíscio", "continente":"africa", "idioma":"Somali e árabe" },
  { "nome":"Sudão", "endonimo":"As-Sūdān (السودان)", "iso":"sd", "capital":"Cartum", "continente":"africa", "idioma":"Árabe e inglês" },
  { "nome":"Sudão do Sul", "endonimo":"South Sudan", "iso":"ss", "capital":"Juba", "continente":"africa", "idioma":"Inglês" },
  { "nome":"Tanzânia", "endonimo":"Tanzania", "iso":"tz", "capital":"Dodoma", "continente":"africa", "idioma":"Suaíli e inglês" },
  { "nome":"Togo", "endonimo":"Togo", "iso":"tg", "capital":"Lomé", "continente":"africa", "idioma":"Francês" },
  { "nome":"Tunísia", "endonimo":"Tūnis (تونس)", "iso":"tn", "capital":"Túnis", "continente":"africa", "idioma":"Árabe" },
  { "nome":"Uganda", "endonimo":"Uganda", "iso":"ug", "capital":"Campala", "continente":"africa", "idioma":"Inglês e suaíli" },
  { "nome":"Zâmbia", "endonimo":"Zambia", "iso":"zm", "capital":"Lusaca", "continente":"africa", "idioma":"Inglês" },
  { "nome":"Zimbabué", "endonimo":"Zimbabwe", "iso":"zw", "capital":"Harare", "continente":"africa", "idioma":"Inglês, shona e ndebele" },
  { "nome":"Saara Ocidental", "endonimo":"Aṣ-Ṣaḥrāʾ al-Gharbiyya (الصحراء الغربية)", "iso":"eh", "capital":"Al Aiune", "continente":"africa", "soberania":"estatuto disputado", "idioma":"Árabe" },

  /* ===================== ÁSIA ===================== */
  { "nome":"Afeganistão", "endonimo":"Afghānistān (افغانستان)", "iso":"af", "capital":"Cabul", "continente":"asia", "idioma":"Pastó e dari" },
  { "nome":"Arábia Saudita", "endonimo":"Al-ʿArabiyya as-Suʿūdiyya (السعودية)", "iso":"sa", "capital":"Riade", "continente":"asia", "idioma":"Árabe" },
  { "nome":"Arménia", "endonimo":"Hayastan (Հայաստան)", "iso":"am", "capital":"Erevan", "continente":"asia", "idioma":"Arménio" },
  { "nome":"Azerbaijão", "endonimo":"Azərbaycan", "iso":"az", "capital":"Baku", "continente":"asia", "idioma":"Azeri" },
  { "nome":"Bangladeche", "endonimo":"Bangladesh (বাংলাদেশ)", "iso":"bd", "capital":"Daca", "continente":"asia", "idioma":"Bengali" },
  { "nome":"Barém", "endonimo":"Al-Baḥrayn (البحرين)", "iso":"bh", "capital":"Manama", "continente":"asia", "idioma":"Árabe" },
  { "nome":"Brunei", "endonimo":"Brunei Darussalam", "iso":"bn", "capital":"Bandar Seri Begawan", "continente":"asia", "idioma":"Malaio" },
  { "nome":"Butão", "endonimo":"Druk Yul (འབྲུག་ཡུལ་)", "iso":"bt", "capital":"Timphu", "continente":"asia", "idioma":"Dzongkha" },
  { "nome":"Camboja", "endonimo":"Kâmpuchéa (កម្ពុជា)", "iso":"kh", "capital":"Phnom Penh", "continente":"asia", "idioma":"Khmer" },
  { "nome":"Catar", "endonimo":"Qaṭar (قطر)", "iso":"qa", "capital":"Doha", "continente":"asia", "idioma":"Árabe" },
  { "nome":"Cazaquistão", "endonimo":"Qazaqstan (Қазақстан)", "iso":"kz", "capital":"Astana", "continente":"asia", "idioma":"Cazaque e russo" },
  { "nome":"China", "endonimo":"Zhōngguó (中国)", "iso":"cn", "capital":"Pequim", "continente":"asia", "idioma":"Chinês (mandarim)" },
  { "nome":"Chipre", "endonimo":"Kýpros (Κύπρος) · Kıbrıs", "iso":"cy", "capital":"Nicósia", "continente":"asia", "idioma":"Grego e turco" },
  { "nome":"Coreia do Norte", "endonimo":"Chosŏn (조선)", "iso":"kp", "capital":"Pyongyang", "continente":"asia", "idioma":"Coreano" },
  { "nome":"Coreia do Sul", "endonimo":"Hanguk (한국)", "iso":"kr", "capital":"Seul", "continente":"asia", "idioma":"Coreano" },
  { "nome":"Emirados Árabes Unidos", "endonimo":"Al-Imārāt (الإمارات)", "iso":"ae", "capital":"Abu Dhabi", "continente":"asia", "idioma":"Árabe" },
  { "nome":"Filipinas", "endonimo":"Pilipinas", "iso":"ph", "capital":"Manila", "continente":"asia", "idioma":"Filipino e inglês" },
  { "nome":"Geórgia", "endonimo":"Sakartvelo (საქართველო)", "iso":"ge", "capital":"Tbilisi", "continente":"asia", "idioma":"Georgiano" },
  { "nome":"Iémen", "endonimo":"Al-Yaman (اليمن)", "iso":"ye", "capital":"Sana", "continente":"asia", "idioma":"Árabe" },
  { "nome":"Índia", "endonimo":"Bhārat (भारत) · India", "iso":"in", "capital":"Nova Deli", "continente":"asia", "idioma":"Hindi, inglês (e mais 21)" },
  { "nome":"Indonésia", "endonimo":"Indonesia", "iso":"id", "capital":"Jacarta", "continente":"asia", "idioma":"Indonésio" },
  { "nome":"Irão", "endonimo":"Īrān (ایران)", "iso":"ir", "capital":"Teerão", "continente":"asia", "idioma":"Persa (farsi)" },
  { "nome":"Iraque", "endonimo":"Al-ʿIrāq (العراق) · Êraq", "iso":"iq", "capital":"Bagdade", "continente":"asia", "idioma":"Árabe e curdo" },
  { "nome":"Israel", "endonimo":"Yisra'el (ישראל) · Isrāʼīl", "iso":"il", "capital":"Jerusalém", "continente":"asia", "idioma":"Hebraico (e árabe)" },
  { "nome":"Japão", "endonimo":"Nihon · Nippon (日本)", "iso":"jp", "capital":"Tóquio", "continente":"asia", "idioma":"Japonês" },
  { "nome":"Jordânia", "endonimo":"Al-Urdunn (الأردن)", "iso":"jo", "capital":"Amã", "continente":"asia", "idioma":"Árabe" },
  { "nome":"Koweit", "endonimo":"Al-Kuwayt (الكويت)", "iso":"kw", "capital":"Cidade do Koweit", "continente":"asia", "idioma":"Árabe" },
  { "nome":"Laos", "endonimo":"Lāo (ລາວ)", "iso":"la", "capital":"Vienciana", "continente":"asia", "idioma":"Lao" },
  { "nome":"Líbano", "endonimo":"Lubnān (لبنان)", "iso":"lb", "capital":"Beirute", "continente":"asia", "idioma":"Árabe" },
  { "nome":"Malásia", "endonimo":"Malaysia", "iso":"my", "capital":"Kuala Lumpur", "continente":"asia", "idioma":"Malaio" },
  { "nome":"Maldivas", "endonimo":"Dhivehi Raajje (ދިވެހިރާއްޖެ)", "iso":"mv", "capital":"Malé", "continente":"asia", "idioma":"Divehi" },
  { "nome":"Mongólia", "endonimo":"Mongol Uls (Монгол Улс)", "iso":"mn", "capital":"Ulã Bator", "continente":"asia", "idioma":"Mongol" },
  { "nome":"Myanmar", "endonimo":"Myanma (မြန်မာ)", "iso":"mm", "capital":"Nay Pyi Taw", "continente":"asia", "idioma":"Birmanês" },
  { "nome":"Nepal", "endonimo":"Nepāl (नेपाल)", "iso":"np", "capital":"Catmandu", "continente":"asia", "idioma":"Nepali" },
  { "nome":"Omã", "endonimo":"ʿUmān (عُمان)", "iso":"om", "capital":"Mascate", "continente":"asia", "idioma":"Árabe" },
  { "nome":"Paquistão", "endonimo":"Pākistān (پاکستان)", "iso":"pk", "capital":"Islamabade", "continente":"asia", "idioma":"Urdu e inglês" },
  { "nome":"Palestina", "endonimo":"Filasṭīn (فلسطين)", "iso":"ps", "capital":"Ramala · Jerusalém Oriental", "continente":"asia", "idioma":"Árabe" },
  { "nome":"Quirguistão", "endonimo":"Kyrgyzstan (Кыргызстан)", "iso":"kg", "capital":"Bisqueque", "continente":"asia", "idioma":"Quirguiz e russo" },
  { "nome":"Singapura", "endonimo":"Singapore · Singapura · 新加坡 · சிங்கப்பூர்", "iso":"sg", "capital":"Singapura", "continente":"asia", "idioma":"Inglês, malaio, mandarim, tâmil" },
  { "nome":"Síria", "endonimo":"Sūriyā (سوريا)", "iso":"sy", "capital":"Damasco", "continente":"asia", "idioma":"Árabe" },
  { "nome":"Sri Lanka", "endonimo":"Sri Laṃkā (ශ්‍රී ලංකා · இலங்கை)", "iso":"lk", "capital":"Sri Jayawardenepura Kotte", "continente":"asia", "idioma":"Cingalês e tâmil" },
  { "nome":"Tailândia", "endonimo":"Prathet Thai (ประเทศไทย)", "iso":"th", "capital":"Banguecoque", "continente":"asia", "idioma":"Tailandês" },
  { "nome":"Tajiquistão", "endonimo":"Tojikiston (Тоҷикистон)", "iso":"tj", "capital":"Duchambé", "continente":"asia", "idioma":"Tajique" },
  { "nome":"Timor-Leste", "endonimo":"Timór Lorosa'e · Timor-Leste", "iso":"tl", "capital":"Díli", "continente":"asia", "idioma":"Tétum e português" },
  { "nome":"Turquemenistão", "endonimo":"Türkmenistan", "iso":"tm", "capital":"Asgabate", "continente":"asia", "idioma":"Turcomano" },
  { "nome":"Turquia", "endonimo":"Türkiye", "iso":"tr", "capital":"Ancara", "continente":"asia", "idioma":"Turco" },
  { "nome":"Usbequistão", "endonimo":"Oʻzbekiston", "iso":"uz", "capital":"Tasquente", "continente":"asia", "idioma":"Usbeque" },
  { "nome":"Vietname", "endonimo":"Việt Nam", "iso":"vn", "capital":"Hanói", "continente":"asia", "idioma":"Vietnamita" },
  { "nome":"Taiwan", "endonimo":"Táiwān (臺灣) · Zhōnghuá Mínguó", "iso":"tw", "capital":"Taipé", "continente":"asia", "soberania":"estatuto disputado", "idioma":"Chinês (mandarim)" },
  { "nome":"Hong Kong", "endonimo":"Hēunggóng (香港)", "iso":"hk", "capital":"—", "continente":"asia", "soberania":"China", "idioma":"Cantonês e inglês" },
  { "nome":"Macau", "endonimo":"Macau · Ou Mun (澳門)", "iso":"mo", "capital":"—", "continente":"asia", "soberania":"China", "idioma":"Cantonês e português" },

  /* ===================== AMÉRICA ===================== */
  { "nome":"Antígua e Barbuda", "endonimo":"Antigua and Barbuda", "iso":"ag", "capital":"Saint John's", "continente":"america", "idioma":"Inglês" },
  { "nome":"Argentina", "endonimo":"Argentina", "iso":"ar", "capital":"Buenos Aires", "continente":"america", "idioma":"Espanhol" },
  { "nome":"Baamas", "endonimo":"The Bahamas", "iso":"bs", "capital":"Nassau", "continente":"america", "idioma":"Inglês" },
  { "nome":"Barbados", "endonimo":"Barbados", "iso":"bb", "capital":"Bridgetown", "continente":"america", "idioma":"Inglês" },
  { "nome":"Belize", "endonimo":"Belize", "iso":"bz", "capital":"Belmopan", "continente":"america", "idioma":"Inglês" },
  { "nome":"Bolívia", "endonimo":"Bolivia · Wuliwya · Buliwya", "iso":"bo", "capital":"Sucre", "continente":"america", "idioma":"Espanhol, quíchua e aimará" },
  { "nome":"Brasil", "endonimo":"Brasil", "iso":"br", "capital":"Brasília", "continente":"america", "idioma":"Português" },
  { "nome":"Canadá", "endonimo":"Canada", "iso":"ca", "capital":"Otava", "continente":"america", "idioma":"Inglês e francês" },
  { "nome":"Chile", "endonimo":"Chile", "iso":"cl", "capital":"Santiago", "continente":"america", "idioma":"Espanhol" },
  { "nome":"Colômbia", "endonimo":"Colombia", "iso":"co", "capital":"Bogotá", "continente":"america", "idioma":"Espanhol" },
  { "nome":"Costa Rica", "endonimo":"Costa Rica", "iso":"cr", "capital":"São José", "continente":"america", "idioma":"Espanhol" },
  { "nome":"Cuba", "endonimo":"Cuba", "iso":"cu", "capital":"Havana", "continente":"america", "idioma":"Espanhol" },
  { "nome":"Domínica", "endonimo":"Dominica", "iso":"dm", "capital":"Roseau", "continente":"america", "idioma":"Inglês" },
  { "nome":"El Salvador", "endonimo":"El Salvador", "iso":"sv", "capital":"São Salvador", "continente":"america", "idioma":"Espanhol" },
  { "nome":"Equador", "endonimo":"Ecuador", "iso":"ec", "capital":"Quito", "continente":"america", "idioma":"Espanhol" },
  { "nome":"Estados Unidos", "endonimo":"United States", "iso":"us", "capital":"Washington, D.C.", "continente":"america", "idioma":"Inglês (de facto)" },
  { "nome":"Granada", "endonimo":"Grenada", "iso":"gd", "capital":"Saint George's", "continente":"america", "idioma":"Inglês" },
  { "nome":"Guatemala", "endonimo":"Guatemala", "iso":"gt", "capital":"Cidade da Guatemala", "continente":"america", "idioma":"Espanhol" },
  { "nome":"Guiana", "endonimo":"Guyana", "iso":"gy", "capital":"Georgetown", "continente":"america", "idioma":"Inglês" },
  { "nome":"Haiti", "endonimo":"Haïti · Ayiti", "iso":"ht", "capital":"Porto Príncipe", "continente":"america", "idioma":"Crioulo haitiano e francês" },
  { "nome":"Honduras", "endonimo":"Honduras", "iso":"hn", "capital":"Tegucigalpa", "continente":"america", "idioma":"Espanhol" },
  { "nome":"Jamaica", "endonimo":"Jamaica", "iso":"jm", "capital":"Kingston", "continente":"america", "idioma":"Inglês" },
  { "nome":"México", "endonimo":"México", "iso":"mx", "capital":"Cidade do México", "continente":"america", "idioma":"Espanhol" },
  { "nome":"Nicarágua", "endonimo":"Nicaragua", "iso":"ni", "capital":"Manágua", "continente":"america", "idioma":"Espanhol" },
  { "nome":"Panamá", "endonimo":"Panamá", "iso":"pa", "capital":"Cidade do Panamá", "continente":"america", "idioma":"Espanhol" },
  { "nome":"Paraguai", "endonimo":"Paraguay · Paraguái", "iso":"py", "capital":"Assunção", "continente":"america", "idioma":"Espanhol e guarani" },
  { "nome":"Peru", "endonimo":"Perú · Piruw", "iso":"pe", "capital":"Lima", "continente":"america", "idioma":"Espanhol e quíchua" },
  { "nome":"República Dominicana", "endonimo":"República Dominicana", "iso":"do", "capital":"São Domingos", "continente":"america", "idioma":"Espanhol" },
  { "nome":"Santa Lúcia", "endonimo":"Saint Lucia", "iso":"lc", "capital":"Castries", "continente":"america", "idioma":"Inglês" },
  { "nome":"São Cristóvão e Neves", "endonimo":"Saint Kitts and Nevis", "iso":"kn", "capital":"Basseterre", "continente":"america", "idioma":"Inglês" },
  { "nome":"São Vicente e Granadinas", "endonimo":"Saint Vincent and the Grenadines", "iso":"vc", "capital":"Kingstown", "continente":"america", "idioma":"Inglês" },
  { "nome":"Suriname", "endonimo":"Suriname", "iso":"sr", "capital":"Paramaribo", "continente":"america", "idioma":"Neerlandês" },
  { "nome":"Trindade e Tobago", "endonimo":"Trinidad and Tobago", "iso":"tt", "capital":"Port of Spain", "continente":"america", "idioma":"Inglês" },
  { "nome":"Uruguai", "endonimo":"Uruguay", "iso":"uy", "capital":"Montevideu", "continente":"america", "idioma":"Espanhol" },
  { "nome":"Venezuela", "endonimo":"Venezuela", "iso":"ve", "capital":"Caracas", "continente":"america", "idioma":"Espanhol" },
  { "nome":"Gronelândia", "endonimo":"Kalaallit Nunaat · Grønland", "iso":"gl", "capital":"Nuuk", "continente":"america", "soberania":"Dinamarca", "idioma":"Gronelandês e dinamarquês" },
  { "nome":"Porto Rico", "endonimo":"Puerto Rico", "iso":"pr", "capital":"San Juan", "continente":"america", "soberania":"Estados Unidos", "idioma":"Espanhol e inglês" },
  { "nome":"Bermudas", "endonimo":"Bermuda", "iso":"bm", "capital":"Hamilton", "continente":"america", "soberania":"Reino Unido", "idioma":"Inglês" },
  { "nome":"Aruba", "endonimo":"Aruba", "iso":"aw", "capital":"Oranjestad", "continente":"america", "soberania":"Países Baixos", "idioma":"Neerlandês e papiamento" },
  { "nome":"Curaçao", "endonimo":"Curaçao · Kòrsou", "iso":"cw", "capital":"Willemstad", "continente":"america", "soberania":"Países Baixos", "idioma":"Neerlandês e papiamento" },
  { "nome":"Ilhas Caimão", "endonimo":"Cayman Islands", "iso":"ky", "capital":"George Town", "continente":"america", "soberania":"Reino Unido", "idioma":"Inglês" },

  /* ===================== OCEÂNIA ===================== */
  { "nome":"Austrália", "endonimo":"Australia", "iso":"au", "capital":"Camberra", "continente":"oceania", "idioma":"Inglês (de facto)" },
  { "nome":"Fiji", "endonimo":"Viti · Fiji · Fijī", "iso":"fj", "capital":"Suva", "continente":"oceania", "idioma":"Inglês, fijiano e hindustani" },
  { "nome":"Ilhas Marshall", "endonimo":"Aolepān Aorōkin M̧ajeḷ", "iso":"mh", "capital":"Majuro", "continente":"oceania", "idioma":"Marshalês e inglês" },
  { "nome":"Ilhas Salomão", "endonimo":"Solomon Islands", "iso":"sb", "capital":"Honiara", "continente":"oceania", "idioma":"Inglês" },
  { "nome":"Kiribati", "endonimo":"Kiribati", "iso":"ki", "capital":"Tarawa Sul", "continente":"oceania", "idioma":"Kiribati e inglês" },
  { "nome":"Micronésia", "endonimo":"Micronesia", "iso":"fm", "capital":"Palikir", "continente":"oceania", "idioma":"Inglês" },
  { "nome":"Nauru", "endonimo":"Naoero · Nauru", "iso":"nr", "capital":"Iaren", "continente":"oceania", "idioma":"Nauruano e inglês" },
  { "nome":"Nova Zelândia", "endonimo":"New Zealand · Aotearoa", "iso":"nz", "capital":"Wellington", "continente":"oceania", "idioma":"Inglês, maori e língua gestual" },
  { "nome":"Palau", "endonimo":"Belau · Palau", "iso":"pw", "capital":"Ngerulmud", "continente":"oceania", "idioma":"Palauano e inglês" },
  { "nome":"Papua-Nova Guiné", "endonimo":"Papua Niugini · Papua New Guinea", "iso":"pg", "capital":"Port Moresby", "continente":"oceania", "idioma":"Tok pisin, inglês, hiri motu" },
  { "nome":"Samoa", "endonimo":"Sāmoa", "iso":"ws", "capital":"Apia", "continente":"oceania", "idioma":"Samoano e inglês" },
  { "nome":"Tonga", "endonimo":"Tonga", "iso":"to", "capital":"Nucualofa", "continente":"oceania", "idioma":"Tonganês e inglês" },
  { "nome":"Tuvalu", "endonimo":"Tuvalu", "iso":"tv", "capital":"Funafuti", "continente":"oceania", "idioma":"Tuvaluano e inglês" },
  { "nome":"Vanuatu", "endonimo":"Vanuatu", "iso":"vu", "capital":"Port Vila", "continente":"oceania", "idioma":"Bislama, inglês e francês" },
  { "nome":"Polinésia Francesa", "endonimo":"Polynésie française · Pōrīnetia Farāni", "iso":"pf", "capital":"Papeete", "continente":"oceania", "soberania":"França", "idioma":"Francês" },
  { "nome":"Nova Caledónia", "endonimo":"Nouvelle-Calédonie", "iso":"nc", "capital":"Nouméa", "continente":"oceania", "soberania":"França", "idioma":"Francês" },
  { "nome":"Guam", "endonimo":"Guåhan · Guam", "iso":"gu", "capital":"Hagåtña", "continente":"oceania", "soberania":"Estados Unidos", "idioma":"Inglês e chamorro" },
  { "nome":"Ilhas Cook", "endonimo":"Kūki 'Āirani · Cook Islands", "iso":"ck", "capital":"Avarua", "continente":"oceania", "soberania":"Nova Zelândia (assoc. livre)", "idioma":"Inglês e maori cook" }

];
